### ISSUE TITLE
Make use of previewpopup option?

### ISSUE THREAD

**Issue by tracyone** [AndrewRadev/quickpeek.vim#1]
Latest version of vim support previewpopup which will turn preview window into popup window automatically 

Please `:help previewpopup` for detail.

**Comment by AndrewRadev** [comment]
It does seem like a potentially good idea to use the native "preview" functionality, although I'm having trouble finding out how to activate the preview from the quickfix window. I can see a lot of options to open tags in the preview window and such, but nothing for the quickfix.

Do you know which command can be used to activate a "preview" for the quickfix or location list windows?

**Comment by tracyone** [comment]
First, make sure you can open a preview window for the  quickfix 

Second, `set previewpopup=height:10,width:60,border:off`

Then next time, preview window will be turned into popup window automatically.

**Comment by tracyone** [comment]
see https://github.com/ronakg/quickr-preview.vim/issues/20

**Comment by cs86661** [comment]
`pedit {filename}:{lnum}:{col}` can open popup window in quickfix. :)

**Comment by tracyone** [comment]
@cs86661 how to get filename lnum in quickfix window?

**Comment by cs86661** [comment]
> @cs86661 how to get filename lnum in quickfix window?

Refer from `getqflist-examples` ...
`echo getqflist({'nr':'$', 'all':0})` can get all quickfix list attributes.

**Comment by tracyone** [comment]
ok thx
