### ISSUE TITLE
add support in location-list too

### ISSUE THREAD

**Issue by chinwobble** [AndrewRadev/quickpeek.vim#4]
Great plugin!

Is there anyway this could also work for the location list too?

**Comment by AndrewRadev** [comment]
Thanks :). I'm not sure why you closed the issue, maybe it was just an accident. I'll reopen.

Checking the code, it seems like I tried to implement loclist support, there's code for it, but it wasn't working correctly. I think I figured out why and pushed a fix. Could you check it out and let me know if it works for you? I checked it, but I don't use the location list myself, so there might still be issues with real workflows.

**Comment by chinwobble** [comment]
actually I closed because it was working fine for me.

**Comment by AndrewRadev** [comment]
Well, it wasn't showing popups for me, so I guess I managed to fix something :D. Carry on, then.
